FROM python:3.8-slim

# Set the working directory to /app
WORKDIR /app

# Copy the local requirements.txt to the container
COPY requirements.txt .

# Install the dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the local code to the container
COPY . .

# Expose port 5000
EXPOSE 5000

# Run app.py when the container launches
CMD ["python", "ML_app.py"]
